name:                dynloader
version:             0.1.0.0
github:              "taqenoqo/dynloader"
license:             BSD3
author:              "Taqenoqo"
maintainer:          "ttaakkee@gmail.com"
copyright:           "Copyright (c) 2018, Taqenoqo"

extra-source-files:
- README.md

synopsis:            Dynamically runtime loading packages
category:            System
description:         This is a simple library for dynamically loading other packages at runtime.
                     Please see the README on GitHub at <https://github.com/taqenoqo/dynloader#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - ghc
  - ghc-paths

tests:
  dynloader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynloader
    - hspec
